language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli
install: npm install
deploy:
- provider: codedeploy
  access_key_id: AKIAIE6NDL3KHYAJ4DZQ
  secret_access_key: *70194565147560
  bucket: ''
  key: ''
  bundle_type: ''
  application: dota-lineup-analyzer
  deployment_group: ''
  on: *70194565142680
before_deploy:
- mkdir -p dpl_cd_upload
- mv '' dpl_cd_upload/''
after_deploy:
- node ./src/run.js
